### ISSUE TITLE
Problems displaying events

### ISSUE THREAD

**Issue by henrikjohansen** [sorah/hubot-zabbix#1]
I am having some problems getting this to work against ZBX 2.2.3 ?

These commands work just fine :
zabbix event on <hostname>
zabbix graphs cpu on <hostname>

However 'zabbix events' returns nothing ....

Any ideas in how to troubleshoot this ?

**Comment by henrikjohansen** [comment]
After some debugging it turns out that we have too many active triggers - filtering by severity does the trick and now it works. 

Will do a pull request for that feature if you are interested ...

**Comment by sorah** [comment]
same here, our hubot waits response from zabbix server long time when I requested all events happening.

Pull requests are welcomed! :sparkles:
